package poros.filkom.ub.jadwalujianfilkom.network;

public class data {
//    public static String utsJadwal = "E1.1    @@         @@                         @@                  @@            SI   @@      Etika Profesi                           @@                  B   @@        TIF   @@          Rekayasa & Manajemen Kebutuhan              @@       A\n" +
//            "E1.2    @@         @@                         @@                  @@            SI   @@      Etika Profesi                           @@                  C   @@        TIF   @@          Rekayasa & Manajemen Kebutuhan              @@       C\n" +
//            "E1.3    @@         @@                         @@                  @@            SI   @@      Etika Profesi                           @@                  D   @@        TIF   @@          Rekayasa & Manajemen Kebutuhan              @@       B\n" +
//            "E1.4    @@         @@                         @@                  @@            PTI  @@      Etika Profesi                           @@                  A   @@        TIF   @@          Rekayasa & Manajemen Kebutuhan              @@       E\n" +
//            "E1.5    @@         @@                         @@                  @@            PTI  @@      Etika Profesi                           @@                  B   @@        TIF   @@          Rekayasa & Manajemen Kebutuhan              @@       F\n" +
//            "E2.1    @@         @@                         @@                  @@            TIF  @@      Etika Profesi                           @@                  K   @@        TI    @@          Jaringan Komputer                           @@       A\n" +
//            "E2.2    @@         @@                         @@                  @@            SI   @@      Etika Profesi                           @@                  A   @@        TIF   @@          Rekayasa & Manajemen Kebutuhan              @@       D\n" +
//            "E2.3    @@         @@                         @@                  @@            TIF  @@      Etika Profesi                           @@                   J  @@        SI    @@          Jaringan Komputer                           @@       C\n" +
//            "E2.4    @@         @@                         @@                  @@            TIF  @@      Etika Profesi                           @@                  F   @@        TI    @@          Jaringan Komputer                           @@       B\n" +
//            "E2.5    @@         @@                         @@                  @@            TIF  @@      Etika Profesi                           @@                  A   @@        PTI   @@          Jaringan Komputer                           @@       A\n" +
//            "E2.7    @@         @@                         @@                  @@            TIF  @@      Etika Profesi                           @@                  M   @@        PTI   @@          Jaringan Komputer                           @@       C\n" +
//            "E2.8    @@         @@                         @@                  @@                 @@                                              @@                      @@        PTI   @@           Jaringan Komputer                          @@   B\n" +
//            "E2.9    @@         @@                         @@                  @@            TIF  @@      Etika Profesi                           @@                  R   @@        SI    @@          Jaringan Komputer                           @@       B\n" +
//            "F2.1    @@   TIF   @@  Pemrograman Dasar      @@          B  @@             TIF      @@           Etika Profesi                       @@                 H        @@    TEKOM  @@      Jaringan Komputer                       @@           C\n" +
//            "F2.2    @@   TI    @@  Pemrograman Dasar      @@          A  @@             TIF      @@           Etika Profesi                       @@                 S        @@    TEKOM  @@      Jaringan Komputer                       @@           B\n" +
//            "F2.4    @@   TIF   @@  Pemrograman Dasar      @@          A  @@             TIF      @@           Etika Profesi                       @@                 G        @@    SI     @@      Jaringan Komputer                       @@           A\n" +
//            "F2.5    @@   TIF   @@  Pemrograman Dasar      @@          F  @@             TIF      @@           Etika Profesi                       @@                 L        @@    TEKOM  @@      Jaringan Komputer                       @@           D\n" +
//            "F2.6    @@   SI    @@  Pemrograman Dasar      @@          B  @@             TIF      @@           Etika Profesi                       @@                 D        @@    SI     @@      Jaringan Komputer                       @@           D\n" +
//            "F2.8    @@   SI    @@  Pemrograman Dasar      @@          D  @@             TIF      @@           Etika Profesi                       @@                 E        @@    TEKOM  @@      Sistem Linier                           @@           C\n" +
//            "F2.9    @@   SI    @@  Pemrograman Dasar      @@          E  @@             TIF      @@           Etika Profesi                       @@                  I       @@    TEKOM  @@      Jaringan Komputer                       @@           A\n" +
//            "F3.1    @@   TEKOM @@  Pemrograman Dasar      @@          A  @@             SI       @@           Etika Profesi                       @@                 E        @@    SI     @@      Basis Data Terdistribusi                @@           A\n" +
//            "F3.2    @@   TIF   @@  Pemrograman Dasar      @@          C  @@             SI       @@           Etika Profesi                       @@                 F        @@    TEKOM  @@      Sistem Linier                           @@           A\n" +
//            "F3.3    @@   TEKOM @@  Pemrograman Dasar      @@          B  @@             TIF      @@           Etika Profesi                       @@                 O        @@    SI     @@      Basis Data Terdistribusi                @@           C\n" +
//            "F3.4    @@   TIF   @@  Pemrograman Dasar      @@          D  @@             SI       @@           Etika Profesi                       @@                 G        @@    SI     @@      Basis Data Terdistribusi                @@           B\n" +
//            "F3.5    @@   TIF   @@  Pemrograman Dasar      @@          E  @@             TIF      @@           Etika Profesi                       @@                 B        @@    TEKOM  @@      Sistem Linier                           @@           B\n" +
//            "F3.6    @@   TEKOM @@  Pemrograman Dasar      @@          C  @@             TIF      @@           Etika Profesi                       @@                 Q        @@    TI     @@      Basis data terdistribusi                @@           A\n" +
//            "F3.7    @@   TI    @@  Pemrograman Dasar      @@          B  @@             TIF      @@           Etika Profesi                       @@                 N        @@           @@                                              @@      \n" +
//            "F3.8    @@   TEKOM @@  Pemrograman Dasar      @@          D  @@             TIF      @@           Etika Profesi                       @@                 P        @@           @@                                              @@      \n" +
//            "F3.9    @@   PTI   @@  Pemrograman Dasar      @@          A  @@             TIF      @@           Etika Profesi                       @@                 C        @@           @@                                              @@      \n" +
//            "F3.10   @@   PTI   @@  Pemrograman Dasar      @@          B  @@                      @@                                               @@                          @@           @@                                              @@      \n" +
//            "F3.11   @@   SI    @@  Pemrograman Dasar      @@          A  @@                      @@                                               @@                          @@           @@                                              @@      \n" +
//            "F3.12   @@   SI    @@  Pemrograman Dasar      @@          C  @@                      @@                                               @@                          @@           @@                                              @@      \n" +
//            "E1.1   @@     SI    @@   Pemodelan Proses Bisnis                      @@     E @@  TIF    @@    Keamanan Informasi                                    @@     I @@  TEKOM  @@   Bahasa Inggris                               @@      C\n" +
//            "E1.2   @@     TIF   @@   Sistem Basis Data                            @@     A @@  TIF    @@    Keamanan Informasi                                    @@    H  @@  TEKOM  @@   Bahasa Inggris                               @@      D\n" +
//            "E1.3   @@     TIF   @@   Sistem Basis Data                            @@     B @@  TIF    @@    Keamanan Informasi                                    @@     J @@  PTI    @@   Bahasa Inggris                               @@      C\n" +
//            "E1.4   @@     SI    @@   Pemodelan Proses Bisnis                      @@     B @@  TIF    @@    Keamanan Informasi                                    @@    K  @@  SI     @@   Bahasa Inggris                               @@      B\n" +
//            "E1.5   @@     PTI   @@   Manajemen Pelatihan                          @@     A @@  TI     @@    Keamanan Informasi                                    @@    A  @@  SI     @@   Bahasa Inggris                               @@      D\n" +
//            "E2.1   @@           @@                                                @@       @@  TIF    @@    Keamanan Informasi                                    @@    B  @@  TI     @@   Bahasa Inggris                               @@      A\n" +
//            "E2.2   @@           @@                                                @@       @@  SI     @@    Manajemen Hubungan Pelanggan                          @@    F  @@  TI     @@   Bahasa Inggris                               @@      B\n" +
//            "E2.3   @@           @@                                                @@       @@  TIF    @@    Keamanan Informasi                                    @@    A  @@  PTI    @@   Bahasa Inggris                               @@      A\n" +
//            "E2.4   @@           @@                                                @@       @@  SI     @@    Manajemen Hubungan Pelanggan                          @@    G  @@  SI     @@   Bahasa Inggris                               @@      C\n" +
//            "E2.5   @@           @@                                                @@       @@  SI     @@    Manajemen Hubungan Pelanggan                          @@    E  @@  TEKOM  @@   Bahasa Inggris                               @@      A\n" +
//            "E2.7   @@           @@                                                @@       @@  TIF    @@    Keamanan Informasi                                    @@    C  @@         @@                                                @@     \n" +
//            "E2.8   @@           @@                                                @@       @@  TIF    @@    Arsitektur & Organisasi Komputer                      @@    A  @@         @@                                                @@     \n" +
//            "E2.9   @@           @@                                                @@       @@  TEKOM  @@    Arsitektur & Organisasi Komputer                      @@    A  @@         @@                                                @@     \n" +
//            "F2.1   @@     TIF   @@   Sistem Basis Data                            @@     F @@  TIF    @@    Keamanan Informasi                                    @@    E  @@  TIF    @@   Manajemen Konfigurasi Perangkat Lunak        @@      B\n" +
//            "F2.2   @@     SI    @@   Pemodelan Proses Bisnis                      @@     D @@  TIF    @@    Keamanan Informasi                                    @@    F  @@  TIF    @@   Manajemen Konfigurasi Perangkat Lunak        @@      G\n" +
//            "F2.4   @@     SI    @@   Pemodelan Proses Bisnis                      @@     A @@  TIF    @@    Keamanan Informasi                                    @@    D  @@  TIF    @@   Swarm Intelligence                           @@      A\n" +
//            "F2.5   @@     TIF   @@   Sistem Basis Data                            @@     C @@  TI     @@    Keamanan Informasi                                    @@    B  @@  TIF    @@   Swarm Intelligence                           @@      B\n" +
//            "F2.6   @@     TIF   @@   Sistem Basis Data                            @@     D @@  TIF    @@    Keamanan Informasi                                    @@    G  @@  TIF    @@   Manajemen Konfigurasi Perangkat Lunak        @@      A\n" +
//            "F2.8   @@     PTI   @@   Multimedia Interaktif                        @@     A @@  TEKOM  @@    Arsitektur & Organisasi Komputer                      @@    B  @@  TIF    @@   Manajemen Konfigurasi Perangkat Lunak        @@      C\n" +
//            "F2.9   @@     TIF   @@   Sistem Basis Data                            @@     E @@  TEKOM  @@    Arsitektur & Organisasi Komputer                      @@    C  @@  TIF    @@   Swarm Intelligence                           @@      C\n" +
//            "F3.1   @@     TEKOM @@   Sistem Medis Berbasis Komputer               @@     B @@  SI     @@    Manajemen Hubungan Pelanggan                          @@    B  @@  TIF    @@   Manajemen Konfigurasi Perangkat Lunak        @@      D\n" +
//            "F3.2   @@     SI    @@   Pemodelan Proses Bisnis                      @@     C @@  SI     @@    Manajemen Hubungan Pelanggan                          @@    A  @@  TIF    @@   Manajemen Konfigurasi Perangkat Lunak        @@      E\n" +
//            "F3.3   @@     TEKOM @@   Sistem Medis Berbasis Komputer               @@     A @@  SI     @@    Manajemen Hubungan Pelanggan                          @@    D  @@  SI     @@   Bahasa Inggris                               @@      E\n" +
//            "F3.4   @@           @@                                                @@       @@  SI     @@    Manajemen Hubungan Pelanggan                          @@    C  @@  TIF    @@   Manajemen Konfigurasi Perangkat Lunak        @@      F\n" +
//            "F3.5   @@           @@                                                @@       @@         @@                                                          @@       @@  PTI    @@   Bahasa Inggris                   @@      B\n" +
//            "F3.6   @@           @@                                                @@       @@         @@                                                          @@       @@  TEKOM  @@   Bahasa Inggris                   @@      B\n" +
//            "E1.1   @@           @@                                                @@       @@  TIF    @@    Administrasi Sistem Server                            @@    C  @@   TIF    @@  Pemrograman Platform Khusus                  @@      A\n" +
//            "E1.2   @@           @@                                                @@       @@  TEKOM  @@    Pengantar Ilmu Komputer                               @@    B  @@   TIF    @@  Pemrograman Platform Khusus                  @@      K\n" +
//            "E1.3   @@           @@                                                @@       @@  TEKOM  @@    Pengantar Ilmu Komputer                               @@    D  @@   TIF    @@  Pemrograman Platform Khusus                  @@      J\n" +
//            "E1.4   @@           @@                                                @@       @@  TEKOM  @@    Pengantar Ilmu Komputer                               @@    A  @@   TIF    @@  Pemrograman Platform Khusus                  @@      N\n" +
//            "E1.5   @@           @@                                                @@       @@  TIF    @@    Pengantar Ilmu Komputer                               @@    F  @@   TIF    @@  Pemrograman Platform Khusus                  @@      L\n" +
//            "E2.1   @@           @@                                                @@       @@  TIF    @@    Administrasi Sistem Server                            @@    A  @@   TIF    @@  Pemrograman Platform Khusus                  @@      D\n" +
//            "E2.2   @@           @@                                                @@       @@  TIF    @@    Administrasi Sistem Server                            @@    B  @@   TIF    @@  Pemrograman Platform Khusus                  @@      C\n" +
//            "E2.3   @@           @@                                                @@       @@  TIF    @@    Administrasi Sistem Server                            @@    D  @@   TIF    @@  Pemrograman Platform Khusus                  @@      F\n" +
//            "E2.4   @@           @@                                                @@       @@  SI     @@    Pengantar Ilmu Komputer                               @@    C  @@   TIF    @@  Pemrograman Platform Khusus                  @@      B\n" +
//            "E2.5   @@           @@                                                @@       @@  TI     @@    Pengantar Ilmu Komputer                               @@    B  @@   TIF    @@  Pemrograman Platform Khusus                  @@      E\n" +
//            "E2.7   @@           @@                                                @@       @@  SI     @@    Pengantar Ilmu Komputer                               @@    D  @@   TIF    @@  Pemrograman Platform Khusus                  @@      M\n" +
//            "E2.8   @@           @@                                                @@       @@  SI     @@    Pengantar Ilmu Komputer                               @@    E  @@          @@                                                   @@      \n" +
//            "E2.9   @@           @@                                                @@       @@  TIF    @@    Augmented Dan Virtual Reality                         @@    A  @@          @@                                                   @@      \n" +
//            "F2.1   @@    SI     @@  Implementasi dan Pengujian Sistem Informasi   @@    E @@   TIF    @@    Pengantar Ilmu Komputer                                @@   B   @@ TIF     @@  Metode Formal dalam Rekayasa Perangkat Lunak  @@     C\n" +
//            "F2.2   @@    TI     @@  Implementasi dan Pengujian Sistem Informasi   @@    A @@   TIF    @@    Pengantar Ilmu Komputer                                @@   E   @@ TEKOM   @@  Embedded System                               @@     D\n" +
//            "F2.4   @@    SI     @@  Implementasi dan Pengujian Sistem Informasi   @@    F @@   TI     @@    Pengantar Ilmu Komputer                                @@   A   @@ TEKOM   @@  Embedded System                               @@     C\n" +
//            "F2.5   @@    TI     @@  Implementasi dan Pengujian Sistem Informasi   @@    B @@   PTI    @@    Pengantar Ilmu Komputer                                @@   A   @@ TIF     @@  Metode Formal dalam Rekayasa Perangkat Lunak  @@     B\n" +
//            "F2.6   @@    SI     @@  Implementasi dan Pengujian Sistem Informasi   @@    C @@   TEKOM  @@    Pengantar Ilmu Komputer                                @@   C   @@ TEKOM   @@  Embedded System                               @@     B\n" +
//            "F2.8   @@    SI     @@  Implementasi dan Pengujian Sistem Informasi   @@    D @@   SI     @@    Pengantar Ilmu Komputer                                @@   B   @@ TIF     @@  Metode Formal dalam Rekayasa Perangkat Lunak  @@     A\n" +
//            "F2.9   @@    SI     @@  Implementasi dan Pengujian Sistem Informasi   @@    G @@   SI     @@    Pengantar Ilmu Komputer                                @@   A   @@ TEKOM   @@  Embedded System                               @@     A\n" +
//            "F3.1   @@    SI     @@  Implementasi dan Pengujian Sistem Informasi   @@    A @@   TIF    @@    Augmented Dan Virtual Reality                          @@   B   @@ TIF     @@  Pemrograman Platform Khusus                   @@     H\n" +
//            "F3.2   @@    SI     @@  Implementasi dan Pengujian Sistem Informasi   @@    B @@   TIF    @@    Pengantar Ilmu Komputer                                @@   C   @@ TIF     @@  Pemrograman Platform Khusus                   @@     I\n" +
//            "F3.3   @@    TIF    @@  Analisis Big Data                             @@    A @@   TIF    @@    Augmented Dan Virtual Reality                          @@   C   @@ TIF     @@  Pemrograman Platform Khusus                   @@     G\n" +
//            "F3.4   @@    PTI    @@  Pengembangan Sumber Belajar                   @@    A @@   TIF    @@    Pengantar Ilmu Komputer                                @@   D   @@ PTI     @@  Desain Grafis                                 @@     A\n" +
//            "F3.5   @@    TIF    @@  Analisis Big Data                             @@    D @@   TIF    @@    Pengantar Ilmu Komputer                                @@   A   @@         @@                                                @@ \n" +
//            "F3.6   @@    TIF    @@  Analisis Big Data                             @@    B @@   PTI    @@    Pengantar Ilmu Komputer                                @@   B   @@         @@                                                @@ \n" +
//            "F3.7   @@    TIF    @@  Analisis Big Data                             @@    C @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.8   @@    PTI    @@  Pengembangan Sumber Belajar                   @@    B @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.9   @@    PTI    @@  Pengembangan Sumber Belajar                   @@    C @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.10  @@          @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.11  @@          @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.12  @@          @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E1.1   @@          @@                                                 @@      @@   TEKOM  @@    Matematika Komputasi                                   @@   C   @@ TIF     @@  Rekayasa Perangkat Lunak                      @@     C\n" +
//            "E1.2   @@          @@                                                 @@      @@   TIF    @@    Matematika Komputasi                                   @@   D   @@ TIF     @@  Rekayasa Perangkat Lunak                      @@     J\n" +
//            "E1.3   @@          @@                                                 @@      @@   TEKOM  @@    Matematika Komputasi                                   @@   B   @@ TIF     @@  Rekayasa Perangkat Lunak                      @@     B\n" +
//            "E1.4   @@          @@                                                 @@      @@   TIF    @@    Matematika Komputasi                                   @@   C   @@ TIF     @@  Rekayasa Perangkat Lunak                      @@     I\n" +
//            "E1.5   @@          @@                                                 @@      @@   PTI    @@    Matematika Komputasi                                   @@   B   @@ TIF     @@  Rekayasa Perangkat Lunak                      @@     K\n" +
//            "E2.1   @@          @@                                                 @@      @@   SI     @@    Dasar Desain Antarmuka Pengguna                        @@   C   @@ SI      @@  Enterprise Architecture                       @@     B\n" +
//            "E2.2   @@          @@                                                 @@      @@   TEKOM  @@    Matematika Komputasi                                   @@   D   @@ SI      @@  Enterprise Architecture                       @@     F\n" +
//            "E2.3   @@          @@                                                 @@      @@   TIF    @@    Matematika Komputasi                                   @@   A   @@ SI      @@  Enterprise Architecture                       @@     G\n" +
//            "E2.4   @@          @@                                                 @@      @@   SI     @@    Dasar Desain Antarmuka Pengguna                        @@   D   @@ TIF     @@  Rekayasa Perangkat Lunak                      @@     N\n" +
//            "E2.5   @@          @@                                                 @@      @@   TI     @@    Matematika Komputasi                                   @@   A   @@ TIF     @@  Rekayasa Perangkat Lunak                      @@     L\n" +
//            "E2.7   @@          @@                                                 @@      @@   TI     @@    Matematika Komputasi                                   @@   B   @@ TIF     @@  Rekayasa Perangkat Lunak                      @@     M\n" +
//            "E2.8   @@          @@                                                 @@      @@   SI     @@    Matematika Komputasi                                   @@   E   @@ SI      @@  Enterprise Architecture                       @@     E\n" +
//            "E2.9   @@          @@                                                 @@      @@   TIF    @@    Matematika Komputasi                                   @@   F   @@ TIF     @@  Rekayasa Perangkat Lunak                      @@     H\n" +
//            "F2.1   @@    SI    @@  Manajemen Investasi Teknologi Informasi        @@   C  @@  SI      @@   Dasar Desain Antarmuka Pengguna                         @@  B   T@@ IF      @@ Rekayasa Perangkat Lunak                       @@    G\n" +
//            "F2.2   @@    SI    @@  Manajemen Investasi Teknologi Informasi        @@   A  @@  TIF     @@   Matematika Komputasi                                    @@  B   S@@ I       @@ Enterprise Architecture                        @@    D\n" +
//            "F2.4   @@    SI    @@  Manajemen Investasi Teknologi Informasi        @@   B  @@  TIF     @@   Matematika Komputasi                                    @@  E   S@@ I       @@ Enterprise Architecture                        @@    C\n" +
//            "F2.5   @@    TI    @@  Pemrograman Mobile                             @@   C  @@  SI      @@   Matematika Komputasi                                    @@  C   T@@ IF      @@ Rekayasa Perangkat Lunak                       @@    F\n" +
//            "F2.6   @@    SI    @@  Manajemen Investasi Teknologi Informasi        @@   D  @@  TEKOM   @@   Kewarganegaraan                                         @@  C   T@@ IF      @@ Rekayasa Perangkat Lunak                       @@    D\n" +
//            "F2.8   @@    TI    @@  Pemrograman Mobile                             @@   A  @@  SI      @@   Dasar Desain Antarmuka Pengguna                         @@  A   S@@ I       @@ Enterprise Architecture                        @@    A\n" +
//            "F2.9   @@    TEKOM @@  Manajemen Industri Teknologi Informasi         @@   B  @@  SI      @@   Matematika Komputasi                                    @@  D   T@@ IF      @@ Rekayasa Perangkat Lunak                       @@    E\n" +
//            "F3.1   @@    SI    @@  Manajemen Investasi Teknologi Informasi        @@   F  @@  TIF     @@   Kewarganegaraan                                         @@  A   P@@ TI      @@ Rekayasa Perangkat Lunak                       @@    A\n" +
//            "F3.2   @@    SI    @@  Manajemen Investasi Teknologi Informasi        @@   E  @@  TEKOM   @@   Kewarganegaraan                                         @@  A   T@@ IF      @@ Rekayasa Perangkat Lunak                       @@    A\n" +
//            "F3.3   @@    TIF   @@  Manajemen Industri Teknologi Informasi         @@   A  @@  TIF     @@   Kewarganegaraan                                         @@  B   P@@ TI      @@ Rekayasa Perangkat Lunak                       @@    B\n" +
//            "F3.4   @@    TIF   @@  Manajemen Industri Teknologi Informasi         @@   B  @@  PTI     @@   Matematika Komputasi                                    @@  A    @@         @@                                                @@ \n" +
//            "F3.5   @@    TI    @@  Pemrograman Mobile                             @@   B  @@  SI      @@   Matematika Komputasi                                    @@  A    @@         @@                                                @@ \n" +
//            "F3.6   @@          @@                                                 @@      @@  SI      @@   Matematika Komputasi                                    @@  B    @@         @@                                                @@ \n" +
//            "F3.7   @@          @@                                                 @@      @@  TEKOM   @@   Matematika Komputasi                                    @@  A    @@         @@                                                @@ \n" +
//            "F3.8   @@          @@                                                 @@      @@  TEKOM   @@   Kewarganegaraan                                         @@  B    @@         @@                                                @@ \n" +
//            "F3.9    @@           @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.10   @@           @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.11   @@           @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.12   @@           @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E1.1   @@    TIF   @@  Sistem Operasi                                 @@   B  @@  TIF     @@   Administrasi Jaringan                                   @@  A   T@@ IF      @@ Pemrograman Aplikasi Perangkat Bergerak        @@    A\n" +
//            "E1.2   @@    TIF   @@  Sistem Operasi                                 @@   C  @@  TIF     @@   Administrasi Jaringan                                   @@  B   T@@ IF      @@ Pemrograman Aplikasi Perangkat Bergerak        @@    B\n" +
//            "E1.3   @@    TIF   @@  Sistem Operasi                                 @@   E  @@  TIF     @@   Administrasi Jaringan                                   @@  C   T@@ IF      @@ Pemrograman Aplikasi Perangkat Bergerak        @@    E\n" +
//            "E1.4   @@    SI    @@  Data Warehouse                                 @@   A  @@  TIF     @@   Logika Fuzzy                                            @@  C   T@@ IF      @@ Pemrograman Aplikasi Perangkat Bergerak        @@    G\n" +
//            "E1.5   @@    SI    @@  Data Warehouse                                 @@   B  @@  TEKOM   @@   Robotika                                                @@  A   T@@ IF      @@ Pemrograman Aplikasi Perangkat Bergerak        @@    H\n" +
//            "E2.1   @@    TIF   @@  Sistem Operasi                                 @@   D  @@  TIF     @@   Logika Fuzzy                                            @@  A   S@@ I       @@ Pengembangan Aplikasi Perangkat Bergerak       @@    A\n" +
//            "E2.2   @@    TIF   @@  Sistem Operasi                                 @@   A  @@  TIF     @@   Logika Fuzzy                                            @@  B   T@@ IF      @@ Pemrograman Aplikasi Perangkat Bergerak        @@    D\n" +
//            "E2.3   @@    TIF   @@  Sistem Operasi                                 @@   F  @@          @@                                                           @@      T@@ IF      @@ Pemrograman Aplikasi Perangkat Bergerak        @@    F\n" +
//            "E2.4   @@          @@                                                 @@      @@          @@                                                           @@      S@@ I       @@ Pengembangan Aplikasi Perangkat Bergerak       @@    D\n" +
//            "E2.5   @@          @@                                                 @@      @@          @@                                                           @@      T@@ IF      @@ Pemrograman Aplikasi Perangkat Bergerak        @@    C\n" +
//            "E2.7   @@          @@                                                 @@      @@          @@                                                           @@      S@@ I       @@ Pengembangan Aplikasi Perangkat Bergerak       @@    B\n" +
//            "E2.8   @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E2.9   @@          @@                                                 @@      @@          @@                                                           @@      S@@ I       @@ Pengembangan Aplikasi Perangkat Bergerak       @@    C\n" +
//            "F2.1   @@    PTI   @@  Pembelajaran Mikro                             @@   B  @@          @@                                                           @@      T@@ I       @@ Dasar Basis Data                               @@    A\n" +
//            "F2.2   @@    TIF   @@  Algoritma Evolusi                              @@   D  @@          @@                                                           @@      S@@ I       @@ Dasar Basis Data                               @@    B\n" +
//            "F2.4   @@    TIF   @@  Algoritma Evolusi                              @@   B  @@          @@                                                           @@      S@@ I       @@ Dasar Basis Data                               @@    A\n" +
//            "F2.5   @@    PTI   @@  Data Warehouse                                 @@   A  @@          @@                                                           @@      P@@ TI      @@ Pengembangan Aplikasi Perangkat Bergerak       @@    A\n" +
//            "F2.6   @@    TIF   @@  Algoritma Evolusi                              @@   A  @@          @@                                                           @@      S@@ I       @@ Dasar Basis Data                               @@    D\n" +
//            "F2.8   @@    TIF   @@  Algoritma Evolusi                              @@   C  @@          @@                                                           @@      T@@ I       @@ Dasar Basis Data                               @@    B\n" +
//            "F2.9   @@    PTI   @@  Pembelajaran Mikro                             @@   A  @@          @@                                                           @@      S@@ I       @@ Dasar Basis Data                               @@    C\n" +
//            "F3.1   @@    SI    @@  Data Warehouse                                 @@   G  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.2   @@    SI    @@  Data Warehouse                                 @@   C  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.3   @@    TEKOM @@  Sistem Operasi                                 @@   B  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.4   @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.5   @@    TEKOM @@  Sistem Operasi                                 @@   A  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.6   @@    SI    @@  Data Warehouse                                 @@   D  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.7   @@    SI    @@  Data Warehouse                                 @@   E  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.8   @@    SI    @@  Data Warehouse                                 @@   F  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.9    @@           @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.10   @@           @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.11   @@           @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.12   @@           @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E1.1   @@    TIF   @@  Metodologi Penelitian Teknologi Informasi      @@   A  @@  SI      @@   Pengembangan Berorientasi Penggunaan Ulang              @@  C    @@         @@                                                @@ \n" +
//            "E1.2   @@    SI    @@  Pengantar Geo Informasi                        @@   A  @@  TIF     @@   Pengenalan Pola                                         @@  B    @@         @@                                                @@ \n" +
//            "E1.3   @@    SI    @@  Pengantar Geo Informasi                        @@   B  @@  TIF     @@   Pengenalan Pola                                         @@  H    @@         @@                                                @@ \n" +
//            "E1.4   @@    PTI   @@  Pengantar Filsafat Ilmu Pendidikan             @@   A  @@  TIF     @@   Pengenalan Pola                                         @@   I   @@         @@                                                @@ \n" +
//            "E1.5   @@    PTI   @@  Pengantar Filsafat Ilmu Pendidikan             @@   B  @@  TIF     @@   Pengenalan Pola                                         @@  E    @@         @@                                                @@ \n" +
//            "E2.1   @@    TIF   @@  Sistem Digital                                 @@   C  @@  SI      @@   Pengembangan Berorientasi Penggunaan Ulang              @@  A    @@         @@                                                @@ \n" +
//            "E2.2   @@    TEKOM @@  Sistem Digital                                 @@   B  @@  SI      @@   Pengembangan Berorientasi Penggunaan Ulang              @@  B    @@         @@                                                @@ \n" +
//            "E2.3   @@    SI    @@  Manajemen & Organisasi                         @@   B  @@  PTI     @@   Desain Web                                              @@  B    @@         @@                                                @@ \n" +
//            "E2.4   @@    SI    @@  Manajemen & Organisasi                         @@   C  @@  PTI     @@   Desain Web                                              @@  C    @@         @@                                                @@ \n" +
//            "E2.5   @@    SI    @@  Manajemen & Organisasi                         @@   D  @@  PTI     @@   Desain Web                                              @@  A    @@         @@                                                @@ \n" +
//            "E2.7   @@    SI    @@  Manajemen & Organisasi                         @@   E  @@  TIF     @@   Pengenalan Pola                                         @@   J   @@         @@                                                @@ \n" +
//            "E2.8   @@          @@                                                 @@      @@  TIF     @@   Pengenalan Pola                                         @@  F    @@         @@                                                @@ \n" +
//            "E2.9   @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F2.1   @@    TIF   @@  Sistem Digital                                 @@   E  @@  TIF     @@   Pengenalan Pola                                         @@  L   S@@ I       @@ Kewirausahaan                                  @@    F\n" +
//            "F2.2   @@    TEKOM @@  Sistem Digital                                 @@   A  @@  TIF     @@   Pengenalan Pola                                         @@  A   S@@ I       @@ Kewirausahaan                                  @@    B\n" +
//            "F2.4   @@    TEKOM @@  Sistem Digital                                 @@   D  @@  TIF     @@   Pengenalan Pola                                         @@  C   S@@ I       @@ Kewirausahaan                                  @@    D\n" +
//            "F2.5   @@    SI    @@  Manajemen & Organisasi                         @@   A  @@  PTI     @@   Pemrograman Basis Data                                  @@  A   T@@ EKOM    @@ Kewirausahaan                                  @@    B\n" +
//            "F2.6   @@    TEKOM @@  Sistem Digital                                 @@   C  @@  TIF     @@   Pengenalan Pola                                         @@  K   P@@ TI      @@ Kewirausahaan                                  @@    A\n" +
//            "F2.8   @@    TIF   @@  Sistem Digital                                 @@   F  @@  TIF     @@   Pengenalan Pola                                         @@  D   S@@ I       @@ Kewirausahaan                                  @@    E\n" +
//            "F2.9   @@    TIF   @@  Sistem Digital                                 @@   B  @@  TIF     @@   Pengenalan Pola                                         @@  G   T@@ IF      @@ Kewirausahaan                                  @@    A\n" +
//            "F3.1   @@    TIF   @@  Sistem Digital                                 @@   D  @@  TEKOM   @@   Sistem Mikrokontroler                                   @@  B   T@@ IF      @@ Desain Kreatif Aplikasi & Game                 @@    A\n" +
//            "F3.2   @@    TI    @@  Statistika                                     @@   A  @@  TEKOM   @@   Sistem Mikrokontroler                                   @@  A   T@@ IF      @@ Desain Kreatif Aplikasi & Game                 @@    B\n" +
//            "F3.3   @@    TI    @@  Statistika                                     @@   B  @@  TIF     @@   Kewirausahaan Teknologi Informasi                       @@  A   T@@ IF      @@ Desain Kreatif Aplikasi & Game                 @@    C\n" +
//            "F3.4   @@    TIF   @@  Sistem Digital                                 @@   A  @@  TIF     @@   Kewirausahaan Teknologi Informasi                       @@  B   P@@ TI      @@ Kewirausahaan                                  @@    B\n" +
//            "F3.5   @@          @@                                                 @@      @@          @@                                                           @@      S@@ I       @@ Kewirausahaan                                  @@    A\n" +
//            "F3.6   @@          @@                                                 @@      @@          @@                                                           @@      T@@ EKOM    @@ Kewirausahaan                                  @@    A\n" +
//            "F3.7   @@          @@                                                 @@      @@          @@                                                           @@      S@@ I       @@ Kewirausahaan                                  @@    C\n" +
//            "F3.8   @@          @@                                                 @@      @@          @@                                                           @@      T@@ I       @@ Kewirausahaan                                  @@    A\n" +
//            "E1.1   @@    TIF   @@  Pembuatan Konten 2D dan 3D                     @@   A  @@  SI      @@   Tata kelola Teknologi Informasi                         @@  B   T@@ IF      @@ Agama Islam                                    @@    K\n" +
//            "E1.2   @@    TIF   @@  Pembuatan Konten 2D dan 3D                     @@   B  @@  TI      @@   Tata kelola Teknologi Informasi                         @@  B   T@@ IF      @@ Agama Islam                                    @@    H\n" +
//            "E1.3   @@    TIF   @@  Pembuatan Konten 2D dan 3D                     @@   C  @@  SI      @@   Tata kelola Teknologi Informasi                         @@  A   T@@ IF      @@ Agama Islam                                    @@    G\n" +
//            "E1.4   @@    PTI   @@  Perencanaan Pembelajaran                       @@   C  @@  TEKOM   @@   Pemrosesan Parallel                                     @@  B   T@@ IF      @@ Agama Islam                                    @@    D\n" +
//            "E1.5   @@    PTI   @@  Perencanaan Pembelajaran                       @@   B  @@  TI      @@   Tata kelola Teknologi Informasi                         @@  A   P@@ TI      @@ Agama Katholik                                 @@    A\n" +
//            "E2.1   @@    SI    @@  Dasar Pengembangan Sistem Informasi            @@   D  @@  SI      @@   Tata kelola Teknologi Informasi                         @@  F   T@@ IF      @@ Agama Islam                                    @@    Q\n" +
//            "E2.2   @@    SI    @@  Dasar Pengembangan Sistem Informasi            @@   A  @@  SI      @@   Tata kelola Teknologi Informasi                         @@  D   T@@ IF      @@ Agama Islam                                    @@    R\n" +
//            "E2.3   @@    SI    @@  Dasar Pengembangan Sistem Informasi            @@   C  @@  TIF     @@   Metode Numerik                                          @@  A   P@@ TI      @@ Agama Kristen Protestan                        @@    B\n" +
//            "E2.4   @@    SI    @@  Dasar Pengembangan Sistem Informasi            @@   B  @@  TEKOM   @@   Metode Numerik                                          @@  A   P@@ TI      @@ Agama Hindu                                    @@    A\n" +
//            "E2.5   @@    PTI   @@  Perencanaan Pembelajaran                       @@   A  @@  TIF     @@   Pengolahan Citra Digital                                @@  B   P@@ TI      @@ Agama Kristen Protestan                        @@    A\n" +
//            "E2.7   @@    TI    @@  Dasar Pengembangan Sistem Informasi            @@   B  @@  TEKOM   @@   Metode Numerik                                          @@  B   T@@ IF      @@ Agama Islam                                    @@    A\n" +
//            "E2.8   @@    PTI   @@  Pembuatan Konten 3D                            @@   A  @@  SI      @@   Tata kelola Teknologi Informasi                         @@  E   P@@ TI      @@ Agama Budha                                    @@    A\n" +
//            "E2.9   @@    TI    @@  Dasar Pengembangan Sistem Informasi            @@   A  @@  SI      @@   Tata kelola Teknologi Informasi                         @@  H   P@@ TI      @@ Agama Islam                                    @@    A\n" +
//            "F2.1   @@          @@                                                 @@      @@  TIF     @@   Metode Numerik                                          @@  B   T@@ IF      @@ Agama Islam                                    @@    L\n" +
//            "F2.2   @@          @@                                                 @@      @@  TIF     @@   Metode Numerik                                          @@  F   T@@ IF      @@ Agama Islam                                    @@    M\n" +
//            "F2.4   @@          @@                                                 @@      @@  SI      @@   Tata kelola Teknologi Informasi                         @@  C   T@@ I       @@ Agama Islam                                    @@    A\n" +
//            "F2.5   @@          @@                                                 @@      @@  PTI     @@   Komputer Terapan                                        @@  B   T@@ IF      @@ Agama Islam                                    @@    O\n" +
//            "F2.6   @@          @@                                                 @@      @@  TIF     @@   Metode Numerik                                          @@  D   T@@ IF      @@ Agama Islam                                    @@    E\n" +
//            "F2.8   @@          @@                                                 @@      @@  TIF     @@   Pengolahan Citra Digital                                @@  A   T@@ IF      @@ Agama Islam                                    @@    B\n" +
//            "F2.9   @@          @@                                                 @@      @@  TEKOM   @@   Pemrosesan Parallel                                     @@  A   T@@ I       @@ Agama Islam                                    @@    B\n" +
//            "F3.1   @@          @@                                                 @@      @@  SI      @@   Tata kelola Teknologi Informasi                         @@  G   T@@ IF      @@ Agama Islam                                    @@    S\n" +
//            "F3.2   @@          @@                                                 @@      @@  TIF     @@   Metode Numerik                                          @@  C   T@@ IF      @@ Agama Islam                                    @@    I\n" +
//            "F3.3   @@          @@                                                 @@      @@  TIF     @@   Metode Numerik                                          @@  E   T@@ IF      @@ Agama Islam                                    @@    J\n" +
//            "F3.4   @@          @@                                                 @@      @@  TEKOM   @@   Metode Numerik                                          @@  C   T@@ IF      @@ Agama Islam                                    @@    N\n" +
//            "F3.5   @@          @@                                                 @@      @@  PTI     @@   Komputer Terapan                                        @@  A   T@@ IF      @@ Agama Islam                                    @@    P\n" +
//            "F3.6   @@          @@                                                 @@      @@          @@                                                           @@      T@@ IF      @@ Agama Islam                                    @@    F\n" +
//            "F3.7   @@          @@                                                 @@      @@          @@                                                           @@      T@@ IF      @@ Agama Islam                                    @@    C\n" +
//            "F3.8   @@          @@                                                 @@      @@          @@                                                           @@      P@@ TI      @@ Agama Islam                                    @@    B\n" +
//            "F3.9   @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.10  @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.11  @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.12  @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E1.1   @@    TIF   @@  Pendidikan Pancasila                           @@   E  @@  TIF     @@   Keamanan Jaringan                                       @@  B   T@@ IF      @@ Text Mining                                    @@    A\n" +
//            "E1.2   @@    SI    @@  Pendidikan Pancasila                           @@   F  @@  TIF     @@   Keamanan Jaringan                                       @@  C   T@@ IF      @@ Text Mining                                    @@    E\n" +
//            "E1.3   @@    SI    @@  Pendidikan Pancasila                           @@   C  @@  TIF     @@   Keamanan Jaringan                                       @@  A   T@@ IF      @@ Text Mining                                    @@    B\n" +
//            "E1.4   @@    SI    @@  Pendidikan Pancasila                           @@   B  @@  TIF     @@   Rekayasa Embedded System                                @@  D   T@@ IF      @@ Text Mining                                    @@    D\n" +
//            "E1.5   @@    SI    @@  Pendidikan Pancasila                           @@   D  @@  PTI     @@   Keamanan Jaringan                                       @@  A   T@@ IF      @@ Text Mining                                    @@    C\n" +
//            "E2.1   @@    TIF   @@  Pendidikan Pancasila                           @@   C  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E2.2   @@    TIF   @@  Pendidikan Pancasila                           @@   A  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E2.3   @@    TIF   @@  Pendidikan Pancasila                           @@   D  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E2.4   @@    SI    @@  Pendidikan Pancasila                           @@   E  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E2.5   @@    TIF   @@  Pendidikan Pancasila                           @@   B  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E2.7   @@    TIF   @@  Pendidikan Pancasila                           @@   F  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E2.8               @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E2.9   @@    SI    @@  Pendidikan Pancasila                           @@   A  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F2.1   @@    TI    @@  Pemrograman Integratif                         @@   A  @@  TIF     @@   Rekayasa Embedded System                                @@  B   T@@ IF      @@ Bahasa Indonesia                               @@    E\n" +
//            "F2.2   @@    TEKOM @@  Sistem Kendali                                 @@   A  @@  SI      @@   Sistem Enterprise                                       @@  A   T@@ EKOM    @@ Bahasa Indonesia                               @@    B\n" +
//            "F2.4   @@    TEKOM @@  Sistem Kendali                                 @@   C  @@  SI      @@   Sistem Enterprise                                       @@  C   T@@ IF      @@ Bahasa Indonesia                               @@    B\n" +
//            "F2.5   @@    PTI   @@  Pemrograman Integratif                         @@   A  @@  TIF     @@   Rekayasa Embedded System                                @@  E   P@@ TI      @@ Perkembangan Peserta Didik                     @@    B\n" +
//            "F2.6   @@    TEKOM @@  Sistem Kendali                                 @@   D  @@  SI      @@   Sistem Enterprise                                       @@  F   T@@ EKOM    @@ Bahasa Indonesia                               @@    A\n" +
//            "F2.8   @@    TEKOM @@  Sistem Kendali                                 @@   B  @@  SI      @@   Sistem Enterprise                                       @@  G   T@@ IF      @@ Bahasa Indonesia                               @@    F\n" +
//            "F2.9   @@    TIF   @@  Sistem Komputasi Terdistribusi                 @@   A  @@  SI      @@   Sistem Enterprise                                       @@  B   P@@ TI      @@ Perkembangan Peserta Didik                     @@    A\n" +
//            "F3.1   @@    TI    @@  Pemrograman Integratif                         @@   B  @@  SI      @@   Sistem Enterprise                                       @@  D   T@@ IF      @@ Bahasa Indonesia                               @@    A\n" +
//            "F3.2   @@          @@                                                 @@      @@  SI      @@   Sistem Enterprise                                       @@  E   T@@ EKOM    @@ Bahasa Indonesia                               @@    C\n" +
//            "F3.3   @@          @@                                                 @@      @@  TIF     @@   Rekayasa Embedded System                                @@  C   T@@ IF      @@ Bahasa Indonesia                               @@    C\n" +
//            "F3.4   @@          @@                                                 @@      @@  TIF     @@   Rekayasa Embedded System                                @@  A   T@@ IF      @@ Bahasa Indonesia                               @@    D\n" +
//            "F3.5   @@          @@                                                 @@      @@          @@                                                           @@      T@@ EKOM    @@ Bahasa Indonesia                               @@    D\n" +
//            "F3.6   @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.7   @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.8   @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.9   @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.10  @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.11  @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.12  @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E1.1   @@    TIF   @@  Web Semantik                                   @@   E  @@          @@                                                           @@      T@@ IF      @@ Sistem Pakar                                   @@    A\n" +
//            "E1.2   @@    TIF   @@  Algoritma & Struktur Data                      @@   F  @@          @@                                                           @@      T@@ IF      @@ Sistem Pakar                                   @@    C\n" +
//            "E1.3   @@    TIF   @@  Web Semantik                                   @@   F  @@          @@                                                           @@      T@@ IF      @@ Sistem Pakar                                   @@    B\n" +
//            "E1.4   @@    SI    @@  Algoritma & Struktur Data                      @@   C  @@          @@                                                           @@      T@@ EKOM    @@ Sistem Cerdas                                  @@    B\n" +
//            "E1.5   @@    SI    @@  Algoritma & Struktur Data                      @@   D  @@          @@                                                           @@      T@@ EKOM    @@ Sistem Cerdas                                  @@    A\n" +
//            "E2.1   @@    TIF   @@  Algoritma & Struktur Data                      @@   C  @@          @@                                                           @@      T@@ EKOM    @@ Sistem Cerdas                                  @@    D\n" +
//            "E2.2   @@    TIF   @@  Algoritma & Struktur Data                      @@   E  @@          @@                                                           @@      T@@ EKOM    @@ Sistem Cerdas                                  @@    C\n" +
//            "E2.3   @@    TIF   @@  Web Semantik                                   @@   C  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E2.4   @@    TIF   @@  Web Semantik                                   @@   D  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E2.5   @@    TIF   @@  Web Semantik                                   @@   G  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E2.7   @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E2.8   @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E2.9   @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F2.1   @@    SI    @@  Algoritma & Struktur Data                      @@   A  @@  TIF     @@   Kriptografi                                             @@  B    @@         @@                                                @@ \n" +
//            "F2.2   @@    SI    @@  Algoritma & Struktur Data                      @@   B  @@  TIF     @@   Kriptografi                                             @@  C    @@         @@                                                @@ \n" +
//            "F2.4   @@    TIF   @@  Algoritma & Struktur Data                      @@   D  @@  TIF     @@   Kriptografi                                             @@  D    @@         @@                                                @@ \n" +
//            "F2.5   @@    TI    @@  Algoritma & Struktur Data                      @@   A  @@  TIF     @@   Kriptografi                                             @@  F    @@         @@                                                @@ \n" +
//            "F2.6   @@    TIF   @@  Web Semantik                                   @@   A  @@  TIF     @@   Kriptografi                                             @@  A    @@         @@                                                @@ \n" +
//            "F2.8   @@    TI    @@  Algoritma & Struktur Data                      @@   B  @@  TEKOM   @@   Teknologi Sistem Cerdas                                 @@  A    @@         @@                                                @@ \n" +
//            "F2.9   @@    TIF   @@  Web Semantik                                   @@   B  @@  TIF     @@   Kriptografi                                             @@  E    @@         @@                                                @@ \n" +
//            "F3.1   @@    TIF   @@  Algoritma & Struktur Data                      @@   A  @@  TI      @@   Administrasi Basis Data                                 @@  B    @@         @@                                                @@ \n" +
//            "F3.2   @@    PTI   @@  Algoritma & Struktur Data                      @@   B  @@  PTI     @@   Administrasi Sistem                                     @@  B    @@         @@                                                @@ \n" +
//            "F3.3   @@    TIF   @@  Algoritma & Struktur Data                      @@   B  @@  PTI     @@   Administrasi Sistem                                     @@  A    @@         @@                                                @@ \n" +
//            "F3.4   @@    PTI   @@  Algoritma & Struktur Data                      @@   A  @@  TI      @@   Administrasi Basis Data                                 @@  A    @@         @@                                                @@ \n" +
//            "F3.5   @@    PTI   @@  Algoritma & Struktur Data                      @@   C  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.6   @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.7   @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.8   @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.9   @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.10  @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.11  @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F3.12  @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E1.1   @@    TIF   @@  Sistem Pendukung Keputusan                     @@   A  @@  TEKOM   @@   Keamanan Komputer                                       @@  A    @@         @@                                                @@ \n" +
//            "E1.2   @@    TIF   @@  Sistem Pendukung Keputusan                     @@   B  @@  TIF     @@   Sistem Multimedia                                       @@  C    @@         @@                                                @@ \n" +
//            "E1.3   @@    SI    @@  Sistem Pendukung Keputusan                     @@   B  @@  TEKOM   @@   Keamanan Komputer                                       @@  B    @@         @@                                                @@ \n" +
//            "E1.4   @@    SI    @@  Sistem Pendukung Keputusan                     @@   A  @@  TIF     @@   Sistem Multimedia                                       @@  B    @@         @@                                                @@ \n" +
//            "E1.5   @@    SI    @@  Sistem Pendukung Keputusan                     @@   G  @@  TIF     @@   Sistem Multimedia                                       @@  A    @@         @@                                                @@ \n" +
//            "E2.1   @@    PTI   @@  Evaluasi Pembelajaran Teknologi Informasi      @@   A  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E2.2   @@    TIF   @@  Sistem Pendukung Keputusan                     @@   C  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E2.3   @@    TIF   @@  Jaringan Nirkabel                              @@   E  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E2.4   @@    PTI   @@  Evaluasi Pembelajaran Teknologi Informasi      @@   B  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E2.5   @@    TIF   @@  Jaringan Nirkabel                              @@   A  @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E2.7   @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E2.8   @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "E2.9   @@            @@                                                 @@      @@          @@                                                           @@       @@         @@                                                @@ \n" +
//            "F2.1   @@    TIF   @@  Jaringan Nirkabel                              @@   D  @@  TIF     @@   Sistem Multimedia                                       @@  D   T@@ IF      @@ Perancangan Game                               @@    C\n" +
//            "F2.2   @@    TIF   @@  Jaringan Nirkabel                              @@   B  @@  TIF     @@   Sistem Multimedia                                       @@  E   T@@ IF      @@ Perancangan Game                               @@    B\n" +
//            "F2.4   @@    SI    @@  Sistem Pendukung Keputusan                     @@   E  @@  TIF     @@   Rekayasa Pengetahuan                                    @@  D   T@@ IF      @@ Perancangan Game                               @@    A\n" +
//            "F2.5   @@    SI    @@  Sistem Pendukung Keputusan                     @@   D  @@  TI      @@   Pemrograman Visual                                      @@  B   T@@ EKOM    @@ Wireless Sensor Network                        @@    A\n" +
//            "F2.6   @@    TIF   @@  Jaringan Nirkabel                              @@   C  @@  TIF     @@   Rekayasa Pengetahuan                                    @@  A   T@@ EKOM    @@ Rangkaian & Elektronika                        @@    C\n" +
//            "F2.8   @@    SI    @@  Sistem Pendukung Keputusan                     @@   C  @@  TIF     @@   Rekayasa Pengetahuan                                    @@  E   T@@ I       @@ Sistem Terdistribusi                           @@    A\n" +
//            "F2.9   @@    SI    @@  Sistem Pendukung Keputusan                     @@   F  @@  TI      @@   Pemrograman Visual                                      @@  A   P@@ TI      @@ Desain dan Pengembangan E-learning             @@    A\n" +
//            "F3.1   @@          @@                                                 @@      @@   TIF    @@    Rekayasa Pengetahuan                                   @@   B   @@ TEKOM   @@  Rangkaian & Elektronika                       @@     A\n" +
//            "F3.2   @@          @@                                                 @@      @@   TIF    @@    Rekayasa Pengetahuan                                   @@   C   @@ TEKOM   @@  Rangkaian & Elektronika                       @@     B\n";
}
